name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  run-devops-ai:
    runs-on: ubuntu-latest

    env:
      GROQ_API_ENDPOINT: ${{ secrets.GROQ_API_ENDPOINT }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.13.0
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.0

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Run DevOps AI Team
      run: python main.py

    - name: Start Docker Container
      run: |
        echo "🔁 Listing images..."
        docker images
        image_tag=$(docker images | grep myapp | awk '{print $1 ":" $2}' | head -n 1)
        echo "🔧 Running container from image: $image_tag"
        docker run -d -p 80:80 "$image_tag"
        sleep 5

    - name: Test Docker Container
      run: |
        if docker ps | grep -q myapp; then
          echo "🔍 Testing Docker container endpoints..."

          if curl -I http://localhost/talkitdoit.html | grep -q "200 OK"; then
            echo "✅ talkitdoit.html test passed! 🚀"
          else
            echo "❌ talkitdoit.html test failed 😢"
            exit 1
          fi

          if curl -I http://localhost/index.html | grep -q "200 OK"; then
            echo "✅ index.html test passed! 🎯"
          else
            echo "❌ index.html test failed 😢"
            exit 1
          fi

          echo "🎉 All Docker container tests passed successfully! 🌟"
        else
          echo "⚠️ Docker container not running, skipping tests 🤔"
          exit 1
        fi
